import Get from './Get';
import Post from './Post';
import Put from './Put';
import Delete from './Delete';
import { userData, userLogin, userLogout, userDelete, userCreate, userEdit, userChangePassword, employeeLoginData } from './Auth';
import {
    getHRDashboard,
    getBranch,
    getDivision,
    getPosition,
    getTeamGroup,
    getTeamGroupByDivisionID,
    getWorkLocation,
    getWorkShift,
    getEmployee,
    getEmployeeByEmail,
    getEmployeeByTeamGroupID,
    getAllWorkLocation,
    getWorkShiftByTeamGroupID,
    getGroupScheduleInfo,
    getScheduleByTeamGroupID,
    getEmployeeScheduleAtMonth,
    getHolidaysAtMonth,
    checkTodayScheduleOfEmployee,
    checkTodayAttendanceOfEmployee,
    getHoliday,
    getSetupOvertime,
    getEmployeeOvertimeRequest,
    getAllOvertimeDayTypes,
    getOvertimeSchemes,

    addBranch,
    addDivision,
    addPosition,
    addTeamGroup,
    addWorkLocation,
    addWorkShift,
    addHoliday,
    addEmployee,
    addSchedule,
    addTimeIn,
    addTimeOut,
    addSetupOvertime,
    addOvertimeSchemes,
    
    editBranch,
    editDivision,
    editPosition,
    editTeamGroup,
    editWorkLocation,
    editWorkShift,
    editHoliday,
    editEmployee,
    editSchedule,
    editSetupOvertime,
    editOvertimeSchemes,

    deleteBranch,
    deleteDivision,
    deletePosition,
    deleteTeamGroup,
    deleteWorkLocation,
    deleteWorkShift,
    deleteHoliday,
    deleteEmployee,
    deleteSchedule,
    deleteScheduleEmployeeAtMonth,

    copySchedule,
} from './HR';


const API = {
    userLogin,
    userLogout,
    userData,
    userCreate,
    userEdit,
    userDelete,
    userChangePassword,
    employeeLoginData,
    getHRDashboard,
    getBranch,
    getDivision,
    getPosition,
    getTeamGroup,
    getTeamGroupByDivisionID,
    getWorkLocation,
    getWorkShift,
    getHoliday,
    getEmployee,
    getEmployeeByEmail,
    getEmployeeByTeamGroupID,
    getWorkShiftByTeamGroupID,
    getAllWorkLocation,
    getGroupScheduleInfo,
    getScheduleByTeamGroupID,
    getEmployeeScheduleAtMonth,
    getHolidaysAtMonth,
    checkTodayScheduleOfEmployee,
    checkTodayAttendanceOfEmployee,
    getEmployeeOvertimeRequest,
    getSetupOvertime,
    getAllOvertimeDayTypes,
    getOvertimeSchemes,

    addBranch,
    addDivision,
    addPosition,
    addTeamGroup,
    addWorkLocation,
    addWorkShift,
    addHoliday,
    addEmployee,
    addSchedule,
    addTimeIn,
    addTimeOut,
    addSetupOvertime,
    addOvertimeSchemes,

    editBranch,
    editDivision,
    editPosition,
    editTeamGroup,
    editWorkLocation,
    editWorkShift,
    editHoliday,
    editEmployee,
    editSchedule,
    editSetupOvertime,
    editOvertimeSchemes,

    deleteBranch,
    deleteDivision,
    deletePosition,
    deleteTeamGroup,
    deleteWorkLocation,
    deleteWorkShift,
    deleteHoliday,
    deleteEmployee,
    deleteSchedule,
    deleteScheduleEmployeeAtMonth,
    copySchedule,
}


export default API;

export * from './Auth'