import Get from './Get';
import Post from './Post';
import Put from './Put';
import Delete from './Delete';
import { userData, userLogin, userLogout, userDelete, userCreate, userEdit, userChangePassword, employeeLoginData } from './Auth';
import {
    getHRDashboard,
    getBranch,
    getDivision,
    getPosition,
    getTeamGroup,
    getTeamGroupByDivisionID,
    getWorkLocation,
    getWorkShift,
    getEmployee,
    getEmployeeByTeamGroupID,
    getAllWorkLocation,
    getWorkShiftByTeamGroupID,
    getGroupScheduleInfo,
    getScheduleByTeamGroupID,
    addBranch,
    addDivision,
    addPosition,
    addTeamGroup,
    addWorkLocation,
    addWorkShift,
    addEmployee,
    addSchedule,
    
    editBranch,
    editDivision,
    editPosition,
    editTeamGroup,
    editWorkLocation,
    editWorkShift,
    editEmployee,
    editSchedule,

    deleteBranch,
    deleteDivision,
    deletePosition,
    deleteTeamGroup,
    deleteWorkLocation,
    deleteWorkShift,
    deleteEmployee,
    deleteSchedule,
    deleteScheduleEmployeeAtMonth,

    copySchedule,
} from './HR';


const API = {
    userLogin,
    userLogout,
    userData,
    userCreate,
    userEdit,
    userDelete,
    userChangePassword,
    employeeLoginData,
    getHRDashboard,
    getBranch,
    getDivision,
    getPosition,
    getTeamGroup,
    getTeamGroupByDivisionID,
    getWorkLocation,
    getWorkShift,
    getEmployee,
    getEmployeeByTeamGroupID,
    getWorkShiftByTeamGroupID,
    getAllWorkLocation,
    getGroupScheduleInfo,
    getScheduleByTeamGroupID,
    addBranch,
    addDivision,
    addPosition,
    addTeamGroup,
    addWorkLocation,
    addWorkShift,
    addEmployee,
    addSchedule,
    editBranch,
    editDivision,
    editPosition,
    editTeamGroup,
    editWorkLocation,
    editWorkShift,
    editEmployee,
    editSchedule,
    deleteBranch,
    deleteDivision,
    deletePosition,
    deleteTeamGroup,
    deleteWorkLocation,
    deleteWorkShift,
    deleteEmployee,
    deleteSchedule,
    deleteScheduleEmployeeAtMonth,
    copySchedule,
}


export default API;

export * from './Auth'